theme: minima
title: Real Projects
description: Real
author: Justin Yeung
markdown: kramdown


exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

