theme: minima
title: Real Projects
description: Projects, in general, are captivating ventures that ignite our creativity and drive us towards achieving meaningful goals. They provide structure, purpose, and opportunities for growth, allowing us to leave a lasting impact on the world. However, upon deeper reflection, an existential crisis emerges, questioning the true significance of our endeavors in the vastness of the universe. The transient nature of life and the fleetingness of projects cast doubts on their ultimate meaning. Yet, amidst the existential turmoil, a glimmer of hope emerges, suggesting that the true value lies in the personal transformation and self-discovery that projects facilitate, even if their impact may be temporary in the grand scheme of things.
author: Justin Yeung
markdown: kramdown


exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

